name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - name: Upload AUModPack.dll artifact
        uses: actions/upload-artifact@v4
        with:
          name: AUModPack.dll
          path: /home/runner/work/AUModPack/AUModPack/src/bin/Release/net6.0/AUModPack.dll

      - name: Download and extract BepInEx
        run: |
          wget -O BepInEx_x64.zip https://builds.bepinex.dev/projects/bepinex_be/735/BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.735%2B5fef357.zip
          unzip BepInEx_x64.zip -d BepInEx_x64
          wget -O BepInEx_x86.zip https://builds.bepinex.dev/projects/bepinex_be/735/BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.735%2B5fef357.zip
          unzip BepInEx_x86.zip -d BepInEx_x86

      - name: Copy AUModPack.dll to BepInEx/plugins
        run: |
          chmod -R 755 BepInEx_x86
          chmod -R 755 BepInEx_x64
          cp /home/runner/work/AUModPack/AUModPack/src/bin/Release/net6.0/AUModPack.dll BepInEx_x86/BepInEx/plugins/
          cp /home/runner/work/AUModPack/AUModPack/src/bin/Release/net6.0/AUModPack.dll BepInEx_x64/BepInEx/plugins/

      - name: Upload AUMP-v1.3.4.zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: AUMP-v1.3.4
          path: BepInEx_x86
          